FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2022

SHELL ["powershell", "-Command"]

RUN Invoke-WebRequest -Uri https://files.jrsoftware.org/is/6/innosetup-6.2.1.exe -OutFile innosetup.exe; \
    Start-Process -FilePath innosetup.exe -ArgumentList '/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', '/SP-' -Wait; \
    Remove-Item -Force innosetup.exe

RUN [System.Environment]::SetEnvironmentVariable('Path', $Env:Path + ';C:\Program Files (x86)\Inno Setup 6', [System.EnvironmentVariableTarget]::Machine)

RUN dotnet tool install --global NetSparkleUpdater.Tools.AppCastGenerator --version 2.8.2

RUN Invoke-WebRequest -Uri https://awscli.amazonaws.com/AWSCLIV2-2.18.13.msi -OutFile AWSCLIV2.msi; \
    Start-Process msiexec.exe -ArgumentList '/i', 'AWSCLIV2.msi', '/quiet', '/norestart' -Wait; \
    Remove-Item -Force AWSCLIV2.msi

WORKDIR /app

# Copy the build-installer directory into the container
COPY build-installer /app/build-installer

CMD ["powershell.exe", "-File", "/app/build-installer/autoBuild.ps1"]