name: SnaptrudeManagerAddin Pipeline

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Commands in Container
        run: |
          docker run --rm \
            -v `${{ github.workspace }}/build-installer:/build-installer` \
            -v `${{ github.workspace }}/revit-addin:/revit-addin` \
            -e CERT_BASE64=`${{ secrets.CERT_BASE64 }} \
            -e CERT_PASSWORD=`${{ secrets.CERT_PASSWORD }} \
            -e AWS_ACCESS_KEY_ID=`${{ secrets.AWS_ACCESS_KEY_ID }}` \
            -e AWS_SECRET_ACCESS_KEY=`${{ secrets.AWS_SECRET_ACCESS_KEY }}` \
            -e AWS_REGION=`${{ secrets.AWS_REGION }}` \
            -e AWS_S3_BUCKET_NAME=`${{ secrets.AWS_S3_BUCKET_NAME }}` \
            -e NETSPARJKE_PUB_KEY=`${{ secrets.NETSPARJKE_PUB_KEY }}` \
            -e NETSPARJKE_PRIV_KEY=`${{ secrets.NETSPARJKE_PRIV_KEY }}` \
            snaptrude-hub/snaptrudemanageraddin-base-image